-- ADD BELOW THIS LINE - Supabase schema for mirrored app data

create table if not exists public.bookings (
    id bigint generated by default as identity primary key,
    name text not null check (char_length(trim(name)) > 0),
    phone text not null check (char_length(trim(phone)) > 0),
    service text not null check (char_length(trim(service)) > 0),
    date text not null check (char_length(trim(date)) > 0),
    time text not null check (char_length(trim(time)) > 0),
    status text not null default 'Pending',
    created_at timestamp with time zone default timezone('utc', now())
);

create table if not exists public.admins (
    id bigint generated by default as identity primary key,
    sqlite_id bigint unique,
    username text not null,
    password text not null,
    role text not null default 'admin',
    created_at timestamp with time zone default timezone('utc', now())
);

-- ADD BELOW THIS LINE - Enable Row Level Security
alter table public.bookings enable row level security;
alter table public.admins enable row level security;

-- ADD BELOW THIS LINE - Safe public booking policy
drop policy if exists "anon_can_insert_bookings" on public.bookings;
create policy "anon_can_insert_bookings"
on public.bookings
for insert
to anon
with check (true);

-- ADD BELOW THIS LINE - Prevent unrestricted public booking reads/writes
drop policy if exists "anon_can_select_bookings" on public.bookings;
drop policy if exists "anon_can_update_bookings" on public.bookings;
drop policy if exists "anon_can_delete_bookings" on public.bookings;

-- ADD BELOW THIS LINE - Insecure admin sync policies (requested exception)
drop policy if exists "anon_can_select_admins_insecure" on public.admins;
create policy "anon_can_select_admins_insecure"
on public.admins
for select
to anon
using (true);

drop policy if exists "anon_can_insert_admins_insecure" on public.admins;
create policy "anon_can_insert_admins_insecure"
on public.admins
for insert
to anon
with check (true);

drop policy if exists "anon_can_update_admins_insecure" on public.admins;
create policy "anon_can_update_admins_insecure"
on public.admins
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_can_delete_admins_insecure" on public.admins;
create policy "anon_can_delete_admins_insecure"
on public.admins
for delete
to anon
using (true);
