-- ==============================================
-- FINAL SUPABASE SCHEMA
-- Completely secures the backend and removes
-- insecure policies.
-- ==============================================

-- 1. BOOKINGS TABLE
create table if not exists public.bookings (
    id bigint generated by default as identity primary key,
    name text not null check (char_length(trim(name)) > 0),
    phone text not null check (char_length(trim(phone)) > 0),
    service text not null check (char_length(trim(service)) > 0),
    date text not null check (char_length(trim(date)) > 0),
    time text not null check (char_length(trim(time)) > 0),
    status text not null default 'Pending',
    created_at timestamp with time zone default timezone('utc', now())
);

-- Enable RLS on Bookings
alter table public.bookings enable row level security;

-- Drop any old booking policies
drop policy if exists "anon_can_insert_bookings" on public.bookings;
drop policy if exists "anon_can_select_bookings" on public.bookings;
drop policy if exists "anon_can_update_bookings" on public.bookings;
drop policy if exists "anon_can_delete_bookings" on public.bookings;
drop policy if exists "allow_public_inserts" on public.bookings;
drop policy if exists "allow_admin_select" on public.bookings;
drop policy if exists "allow_admin_update" on public.bookings;
drop policy if exists "allow_admin_delete" on public.bookings;

-- BOOKING POLICIES
-- Anyone can insert a booking
create policy "allow_public_inserts"
on public.bookings
for insert
to anon, authenticated
with check (true);

-- SECURE: Only logged-in admins can view, update, delete
create policy "allow_admin_select"
on public.bookings
for select
to authenticated
using ( true );

create policy "allow_admin_update"
on public.bookings
for update
to authenticated
using ( true )
with check ( true );

create policy "allow_admin_delete"
on public.bookings
for delete
to authenticated
using ( true );


-- 2. ADMINS TABLE (Role-Based Metadata)
-- The exact association happens natively based on checking the
-- 'email' against auth.users(), avoiding complex nested foreign-key inserts.
create table if not exists public.admins (
    id uuid primary key default gen_random_uuid(),
    email text not null unique,
    role text not null default 'admin',
    created_at timestamp with time zone default timezone('utc', now())
);

-- Enable RLS on Admins
alter table public.admins enable row level security;

-- Drop the insecure admin policies that allowed public access
drop policy if exists "anon_can_select_admins_insecure" on public.admins;
drop policy if exists "anon_can_insert_admins_insecure" on public.admins;
drop policy if exists "anon_can_update_admins_insecure" on public.admins;
drop policy if exists "anon_can_delete_admins_insecure" on public.admins;

-- SECURE: Only authenticated users can manage admin metadata
-- Check: Only 'Main Admin' can view/add/delete admins
create policy "admins_select_policy"
on public.admins
for select
to authenticated
using ( 
    EXISTS (
        SELECT 1 FROM public.admins 
        WHERE email = (select auth.jwt() ->> 'email')
        AND role = 'Main Admin'
    )
    OR email = (select auth.jwt() ->> 'email')
);

create policy "admins_mgmt_policy"
on public.admins
for all
to authenticated
using ( 
    EXISTS (
        SELECT 1 FROM public.admins 
        WHERE email = (select auth.jwt() ->> 'email') 
        AND role = 'Main Admin'
    )
);
